# Generated by Django 3.1.3 on 2020-11-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='body',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='body',
            field=models.TextField(default='A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='campaigns.brand'),
            preserve_default=False,
        ),
    ]
